const Strings = {
	yes: "Ja",
	no: "Nein",
	cancel: "Abbrechen",
	okay: "Okay",
	close: "Schließen",
	try_again: "Erneut versuchen",
	refresh: "Aktualisieren",
	reset: "Zurücksetzen",
	back: "Zurück",
	settings: "Einstellungen",
	save: "Speichern",
	send: "Senden",

	mail: "n.neddermann@hs-osnabrueck.de",
	phone: "0541-969-5017",
	mittelstand_40_lingen_events_url: "https://kompetenzzentrum-lingen.digital/termine",
	mittelstand_40_lingen_url: "https://kompetenzzentrum-lingen.digital",

	app_title: "SmartFarmCheck",
	app_title_short: "FarmCheck",

	screen_title_media_library: "Mediathek",
	screen_title_events: "Angebote",
	screen_title_measure_list: "Digitalisierung",
	screen_title_measure_detail: "Maßnahmeninformation",
	screen_title_form_list: "Digitalisierungschecks",
	screen_title_form: "Angaben zum Betrieb",
	screen_title_form_help: "Hilfe zum Fragebogen",
	screen_title_evaluation: "Ihre Maßnahmenbewertung",
	screen_title_evaluation_detail: "Maßnahmeninformation",
	screen_title_event_detail: "Eventdetails",
	screen_title_video_player: "Videoplayer",
	screen_title_audio_player: "Audioplayer",
	screen_title_settings: "Einstellungen",
	screen_title_about: "Über diese App",
	screen_title_imprint: "Impressum",
	screen_title_privacy: "Datenschutz",
	screen_title_license: "Lizenzen",
	screen_title_contact: "Kontakt",

	information_card_default_title: "Zu Ihrer Information",
	information_card_advice_expand: "Ausklappen für weitere Informationen.",

	digicheck_title: "Unser Digitalisierungscheck",
	digicheck_content: "Anhand verschiedener Fragebögen erhalten Sie Empfehlungen für Digitalisierungsmaßnahmen, basierend auf der Befragung vieler Betriebe.",

	measure_all_measures_title: "Verfügbare Digitalisierungsmaßnahmen:",
	measure_loading: "Laden der aktuellsten Maßnahmen...",
	measure_loading_error: "Aktuell können die Maßnahmen nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
	measure_loading_empty: "Aktuell wurden keine Maßnahmen gefunden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
	measure_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Maßnahmen können daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
	measure_navigate_evaluation: "SmartFarmCheck starten",
	measure_split_content_placeholder: "Wählen Sie eine Maßnahme aus der Liste aus, um weitere Informationen anzuzeigen, oder tippen Sie auf den Button \"SmartFarmCheck starten\", um Empfehlungen berechnen zu lassen.",
    measure_resource_open_error_title: "Abruf-Fehler",
    measure_resource_open_error_description: "Aktuell konnten diese Zusatzinformationen leider nicht abgerufen werden.",
    measure_detail_no_content: "Wir erstellen bereits detaillierte Informationen zu dieser Digitalisierungsmaßnahme und werden sie Ihnen an dieser Stelle zur Verfügung stellen.",

	select_form_loading: "Laden der verfügbaren Digitalisierungschecks...",
	select_form_loading_error: "Aktuell können die Digitalisierungschecks nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
	select_form_loading_empty: "Aktuell konnten keine Digitalisierungschecks gefunden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
	select_form_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Digitalisierungschecks können daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",

	form_loading: "Laden des Fragebogens...",
	form_loading_error: "Aktuell kann der Fragebogen nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
	form_loading_empty: "Aktuell konnten keine Fragen zum Fragebogen gefunden werden. Bitte übeprüfen Sie Ihre Internetverbindung und versuchen Sie es später erneut.",
	form_loading_no_network: "Aktuell besteht keine Internetverbindung. Der Fragebogen kann daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
	form_reset: "Zurücksetzen",
	form_calculate: "Jederzeit berechnen",
	form_paging_backwards: "Zurück",
	form_paging_forwards: "Weiter",
	form_dialog_confirm_reset_title: "Wirklich zurücksetzen?",
	form_dialog_confirm_reset_content: "Wenn Sie den Fragebogen zurücksetzen, werden Ihre bestehenden Eingaben unwiderruflich gelöscht. Möchten Sie dies?",
	form_dialog_empty_title: "Leerer Fragebogen",
	form_dialog_empty_content: "Bein einem gänzlich unausgefülltem Fragebogen können wir Ihnen leider keine Empfehlungen berechnen. Füllen Sie dazu zunächst einige Fragen aus.\n\nFalls Sie sich nur allgemein informieren möchten, können Sie auf dem vorherigen Reiter alle Maßnahmen auswählen.",
	form_dialog_errors_title: "Ungültige Eingaben",
	form_dialog_errors_content: "Bitte berichtigen Sie zuerst die ungültigen Eingaben, bevor Sie den Fragebogen absenden. Ansonsten kann keine korrekte Berechnung erfolgen.",
	form_dialog_send_unfinished_title: "Fragebogen absenden?",
	form_dialog_send_unfinished_content: "Sie haben den Fragebogen noch nicht vollständig ausgefüllt, möchten Sie es trotzdem absenden? Je mehr Fragen Sie beantworten, desto individueller können die Empfehlungen berechnet werden.",
	form_send: "Absenden",
	form_layout_questions: "Fragenlayout",
	form_help: "Hilfe",
	form_input_placeholder: "Hier eingeben...",
	form_calculate_at_any_point_title: "Über den Fragebogen",
	form_calculate_at_any_point_content: "Die Berechnung der Empfehlungen ist jederzeit möglich. Fragen, die Sie nicht betreffen, oder die Sie nicht beantworten möchten können, Sie einfach offen lassen.",

	formselect_available_forms_title: "Verfügbare Digitalisierungschecks:",
	formselect_nothing_fitting_title: "Kein passender Digitalisierungscheck für Sie dabei?",
	formselect_nothing_fitting_content: "Kein Problem! Sie können uns gerne jederzeit mit Ihrem Anliegen kontaktieren. Außerdem arbeiten wir aktuell an weiteren Digitalisierungschecks.",
	formselect_nothing_fitting_goto_contact: "Zum Kontakt",
    formselect_form_comming_soon: "Dieser Fragebogen steht Ihnen demnächst zur Verfügung.",

	evaluation_information_title: "Infos zur Bewertung",
	evaluation_information_text: "Hier sehen Sie die auf der Basis Ihrer Anworten gewichteten Maßnahmen. Möchten Sie sich über eine dieser Maßnahmen informieren, so tippen Sie diese einfach an.",
	evaluation_list_heading: "Die Bewertung:",
	evaluation_loading: "Die Bewertung wird durchgeführt...",
	evaluation_loading_error: "Aktuell kann die Bewertung nicht durchgefürt werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
	evaluation_loading_empty: "Die Auswertung konnte aktuell keine Maßnahmen finden. Bitte überprüfen Sie Ihre Eingaben, beantworten Sie weitere Fragen oder versuchen Sie es später erneut.",
	evaluation_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Auswertung kann daher nicht durchgeführt werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
	evaluation_help: "Fragen? Jetzt Kontakt aufnehmen ",
	evaluation_split_content_placeholder: "Wählen Sie eine Maßnahme aus der Liste aus, um weitere Informationen anzuzeigen.",
	evaluation_generate_pdf: "PDF erstellen",

	evaluation_detail_loading: "Die Maßnahme wird geladen...",
	evaluation_detail_loading_error: "Aktuell kann die Maßnahme leider nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
	evaluation_detail_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Details zur Maßnahme können daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",

	medialibrary: "Erklärvideos",
	medialibrary_loading: "Laden der verfügbaren Erklärvideos...",
	medialibrary_loading_error: "Aktuell können keine Videos geladen werden. Bitte überprüfen Sie Ihre Internetverbindungoder versuchen Sie es später erneut.",
	medialibrary_loading_empty: "Erklärvideos des Kompetenzzentrums werden hier angezeigt. Aktuell wurden keine Videos gefunden. Bitte versuchen Sie es später erneut.",
	medialibrary_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Videos können daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
	medialibrary_watch_now: "Jetzt ansehen",
	medialibrary_no_description_available: "Keine Beschreibung verfügbar.",
	medialibrary_video_cant_be_played: "Das Video kann leider nicht wiedergegeben werden.",

	event_calendar: "Veranstaltungskalendar",
	event_list_heading: "Aktuelle Veranstaltungen:",
	event_loading: "Laden der kommenden Veranstaltungen...",
	event_loading_error: "Aktuell können keine Veranstaltungen geladen werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
	event_loading_empty: "Kommende Veranstaltungen des Kompetenzzentrums werden hier angezeigt. Aktuell stehen keine Veranstaltungen an.",
	event_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Veranstaltungen können daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
	event_no_upcomming_title: "Keine geplanten Veranstaltungen",
	event_no_upcomming_description: "Aktuell sind keine Veranstaltungen geplant. Sobald es Neuigkeiten gibt, werden sie hier angezeigt.",
	event_no_upcomming_alternatives: "Alternativ können Sie auch direkt auf unser Website nach Veranstaltungen suchen oder uns direkt mit Ihrem Anliegen kontaktieren.",
	event_nothing_fitting_title: "Keine passende Veranstaltung für Sie dabei?",
	event_nothing_fitting_content: "Kein Problem! Sie können uns gerne jederzeit mit Ihrem Anliegen kontaktieren.",
	event_nothing_fitting_goto_contact: "Zum Kontakt",
	event_nothing_fitting_goto_website: "Zur Website",
	event_already_in_calendar_title: "Veranstaltung bereits eingetragen",
	event_already_in_calendar_text: "Im Kalender ist bereits eine Veranstaltung mit gleichem Namen und gleichen Zeiten eingetragen, sie wird daher nicht erneut gespeichert.",
	event_no_description_available: "Keine Beschreibung verfügbar.",
	event_details: "Details",
	event_register: "Anmelden",
	event_remember: "Merken",
	event_time_undefined: "Kein Zeitraum bekannt.",
	event_start_or_end_undefined: "[Offen]",
	event_max_participant_1: "Diese Veranstaltung ist auf ",
	event_max_participant_2: " Teilnehmer begrenzt!",
    event_website_url_open_error_title: "Website nicht aufrufbar.",
    event_website_url_open_error_description: "Die Website der Veranstaltungen konnte leider nicht aufgerufen werden. Sie können alternativ gerne auf der Website des Mittelstandes nach den aktuellen Veranstaltungen schauen.",

	calendar_create_new: "[Neuen Kalender erstellen]",
	calendar_select_default: "Standardkalender auswählen",
	permission_calendar: "Kalenderberechtigung",
	permission_calendar_denied: "Fehlende Kalenderberechtigung",
	permission_calendar_information_before: "Nachfolgend wird die Systemberechtigung zum Bearbeiten der Kalender abgefragt. Diese wird benötigt, um automatisch Termine in Ihren Kalender einzutragen.",
	permission_calendar_information_before_denied_permanent: "Sie scheinen die Kalenderberechtigung abgelehnt zu haben, weswegen wir Ihnen leider keine Termine automatisch in Ihren Kalender eintragen dürfen. Sie können diese manuell in den Systemeinstellungen erteilen.",
	permission_calendar_information_after_denied: "Ohne die Berechtigung können wir die Termine für Sie leider nicht in Ihren Kalender eintragen. Alternativ können Sie den Termin natürlich manuell eintragen, oder die Berechtigung bei der nächsten Abfrage erteilen.",
	permission_calendar_information_after_denied_permanent: "Ohne die Berechtigung können wir die Termine für Sie leider nicht in Ihren Kalender eintragen. Wenn Sie sich dennoch umentscheiden können Sie die Berechtigung in den Berechtigungseinstellung Ihres System ändern.",
	calendar_event_added_title: "Veranstaltung erstellt.",
	calendar_event_added_description: "Die Veranstaltung wurde Ihrem Kalender hinzugefügt.",

	settings_appearance_title: "Helles/dunkels Design",
	settings_appearance_description: "Das Design der App passt sich automatisch den eingestellten Präferenzen Ihres Gerätes an.",
	settings_reset_form_title: "Fragebögen zurücksetzen",
	settings_reset_form_description: "Setzen Sie Ihre Eingaben in allen Fragebögen zurück.",
	settings_reset_form_dialog_title: "Alle Fragebögen zurücksetzen?",
	settings_reset_form_dialog_content: "Sind Sie sicher, dass Sie alle Fragebögen zurücksetzen möchten?",
	settings_licenses_title: "Lizenzen",
	settings_licenses_description: "Eine Übersicht der verwendeten Open-Source-Bibliothken.",

	contact_mail_title: "Per Mail",
	contact_mail_description: "Bei allgemeinen Fragen können Sie uns jederzeit per Mail erreichen. Wir werden uns dann entsprechend bei Ihnen zurückmelden.",
	contact_mail_action: "Jetzt E-Mail verfassen",
    contact_mail_error_title: "Ihr Mail-Programm",
    contact_mail_error_description: "Eine automatische Weiterleitung zu Ihrem Mail-Programm war leider nicht möglich. Bitte verfassen Sie die Mail daher manuell.",
	contact_phone_title: "Telefonisch",
	contact_phone_description: "Natürlich können Sie uns auch telefonisch zu den normalen Bürozeiten erreichen.",
	contact_phone: "Nikolas Neddermann\nTel: 0541-969-5017",
	contact_phone_action: "Jetzt anrufen",
    contact_phone_error_title: "Kein Anruf möglich?",
    contact_phone_error_description: "Eine automatische Weiterleitung zu Ihrem Anruf-Wähler war leider nicht möglich. Bitte rufen Sie die Nummer daher manuell an.",
	contact_website_title: "Im Internet",
	contact_website_description: "Auch auf unserer Internetpräsenz erhalten Sie Informationen über uns und unsere Angebote.",
	contact_website_action: "Zur Website",
	contact_website_error_title: "Website-Aufruf nicht möglich.",
	contact_website_error_description: "Die Weiterleitung zu Ihrem Browser war leider nicht möglich. Sie können unsere Website aber gerne Manuell aufrufen: ",
	contact_information_title: "Informationen zur App",
	contact_information_description: "Informationen über Förderer, Impressum und Datenschutz.",
	contact_information_action: "Anzeigen",

	contact_request_loading_error: "Fehler beim Erstellen einer Kontaktanfrage.",
	contact_request_loading_no_network: "Aktuell besteht keine Internetverbindung.",
	contact_request_loading: "Kontaktanfrage wird erstellt...",
	contact_request_success: "Die Kontaktanfrage wurde erfolgreich erstellt. Sie sehen diese dann in Ihrem E-Mail-Postfach. Das Versenden der Kontaktanfrage kann einige Minuten in Anspruch nehmen.",
	contact_request_dialog_empty_title: "Leerer Fragebogen",
	contact_request_dialog_empty_content: "Bein einem gänzlich unausgefülltem Fragebogen wählen Sie bitte den normalen Kontaktweg über die Kontaktoptionen auf dem Kontaktmenüpunkt der Startseite. Sobald Sie einige Fragen beantwortet haben, können Sie auch diesen Kontaktweg verwenden.",

	contact_request_please_enter_mail: "Bitte eine E-Mail eingeben",
	contact_request_please_enter_valid_mail: "Bitte eine gültige E-Mail eingeben.",
	contact_request_mail_is_valid: "Die E-Mail ist gültig. Sie können absenden!",
	contact_request_mail_placeholder: "kontakt@e.mail",

	contact_request_how_it_works_title: "So funktioniert's:",
	contact_request_how_it_works_content_questions: "Sollten beim Beantworten des Fragebogens Fragen aufkommen oder die Ergebnisse der Bewertung unklar bleiben, zögern Sie nicht uns zu kontaktieren!",
	contact_request_how_it_works_content_document: "Um den Austausch mit einem Mitarbeiter des Mittelstand 4.0 Kompetenzzentrums zu vereinfachen, wird zur Übersicht ein Dokument mit Ihren Antworten und den erhaltenen Bewertungen erstellt und an Sie und uns per Mail gesendet.",
	contact_request_about_privacy_title: "Wie ist das mit dem Datenschutz?",
	contact_request_about_privacy_content_document: "Die von Ihnen eingebenen Daten werden zur Auswertung und Generierung des Dokumentes an den Server gesendet, aber NICHT gespeichert; auch nicht die Mail-Adresse. Die Bewertungsdaten sind weiterhin zu jedem Zeitpunkt anonym. Sie werden hinterher lediglich an Ihre und unsere Kontakt-Mail versendet, damit wir mit Ihnen in Konkakt treten können.",
	contact_request_about_privacy_content_advices: "Möchten Sie dennoch einige Daten nicht preisgeben, können Sie die entsprechenden Fragen unausgefüllt lassen. Alternativ können Sie auch eine anonyme Mail-Adresse verwenden.",

	license_under_mit: "Unter der MIT Lizenz",
	license_mit_permission: "Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:",
	license_mit_condition: "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.",
	license_mit_text: " THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",

	privacy: "Datenschutz",
	imprint: "Impressum",
	imprint_mittelstand_4: "Mittelstand 4.0 (Lingen)",
	imprint_mittelstand_digital: "Mittelstand Digital",
	imprint_bmwk: "BMWK",
    imprint_open_url_error_title: "Website nicht aufrufbar",
    imprint_open_url_error_description: "Aktuell kann die Website des Förderers leider nicht aufgerufen werden. Alternativ können Sie über die Suchmaschine Ihrer Wahl nach Informationen suchen."
}

export default Strings
