const Strings = {
    yes: "Ja",
    no: "Nein",
    cancel: "Abbrechen",
    okay: "Okay",
    close: "Schließen",
    try_again: "Erneut versuchen",
    refresh: "Aktualisieren",
    reset: "Zurücksetzen",
    back: "Zurück",
    settings: "Einstellungen",

    mail: "mittelstand40@hs-osnabrueck.de",
    phone: "0541-969-5017",

    main_greeting_title: "Herzlich Willkommen",
    main_greeting_content: "...in der Smartfarmcheck-App! Hier finden Sie unser Weiterbildungsangebot und Maßnahmen zur Digitalisierung, bewertet für Ihren Betrieb.",

    app_title: "SmartFarmCheck",
    app_title_short: "FarmCheck",

    screen_title_media_library: "Mediathek",
    screen_title_events: "Angebote",
    screen_title_measure_list: "Check",
    screen_title_measure_detail: "Maßnahmeninformation",
    screen_title_form_list: "Fragebogenauswahl",
    screen_title_form: "Angaben zum Betrieb",
    screen_title_form_help: "Hilfe zum Fragebogen",
    screen_title_evaluation: "Ihre Maßnahmenbewertung",
    screen_title_evaluation_detail: "Maßnahmeninformation",
    screen_title_event_detail: "Eventdetails",
    screen_title_video_player: "Videoplayer",
    screen_title_audio_player: "Audioplayer",
    screen_title_settings: "Einstellungen",
    screen_title_about: "Über diese App",
    screen_title_imprint: "Impressum",
    screen_title_privacy: "Datenschutz",
    screen_title_license: "Lizenzen",
    screen_title_contact: "Kontakt",

    information_card_default_title: "Zu Ihrer Information",
    information_card_advice_expand: "Ausklappen für weitere Informationen.",

    measure_information_title: "Über die Maßnahmen",
    measure_information_text: "Hier sehen Sie verschiedene Maßnahmen zur Digitalisierung, die sich für mittelständische Landwirtschaftsbetriebe eignen. Gerne können Sie sich über unser Formular persönliche Empfehlungen berechnen lassen oder uns jederzeit kontaktieren.",
    measure_loading: "Laden der aktuellsten Maßnahmen...",
    measure_loading_error: "Aktuell können die Maßnahmen nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
    measure_loading_empty: "Aktuell wurden keine Maßnahmen gefunden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
    measure_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Maßnahmen können daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
    measure_navigate_evaluation: "SmartFarmCheck starten",
    measure_split_content_placeholder: "Wählen Sie eine Maßnahme aus der Liste aus, um weitere Informationen anzuzeigen, oder tippen Sie auf den Button unten, um Empfehlungen berechnen zu lassen.",

    select_form_information_title: "Zur Auswahl des Fragebogens",
    select_form_information_text: "Nachfolgend haben wir für Sie verschiedene, an Branchen und Bereiche angepasste, Fragebögen vorbereitet, anhand derer wir Ihnen angepasste Empfehlungen berechnen können.",
    select_form_loading: "Laden der verfügbaren Formulare...",
    select_form_loading_error: "Aktuell können die Formulare nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
    select_form_loading_empty: "Aktuell wurden keine Formulare gefunden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
    select_form_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Formulare können daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",

    form_loading: "Laden des aktuellsten Fragebogens...",
    form_loading_error: "Aktuell kann das Formular nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
    form_loading_empty: "Aktuell konnten keine Fragen zum Formular gefunden werden. Bitte übeprüfen Sie Ihre Internetverbindung und versuchen Sie es später erneut.",
    form_loading_no_network: "Aktuell besteht keine Internetverbindung. Das aktuelle Formular kann daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
    form_reset: "Zurücksetzten",
    form_calculate: "Jetzt berechnen",
    form_paging_backwards: "Zurück",
    form_paging_forwards: "Weiter",
    form_dialog_confirm_reset_title: "Wirklich zurücksetzten?",
    form_dialog_confirm_reset_content: "Wenn Sie das Formular zurücksetzen, werden Ihre bestehenden Eingaben unwiderruflich gelöscht. Möchten Sie dies?",
    form_dialog_empty_title: "Leeres Formular",
    form_dialog_empty_content: "Bein einem gänzlich unausgefülltem Formular können wir Ihnen leider keine Empfehlungen berechnen. Füllen Sie dazu zunächst einige Fragen aus.\n\nFalls Sie sich nur allgemein informieren möchten, können Sie sich auf dem vorherigen Reiter alle Maßnahmen auswählen.",
    form_dialog_errors_title: "Ungültige Eingaben",
    form_dialog_errors_content: "Bitte berichtigen Sie zuerst die ungültigen Eingaben, bevor Sie das Formular absenden. Ansonsten kann keine korrekte Berechnung erfolgen.",
    form_dialog_send_unfinished_title: "Formular absenden?",
    form_dialog_send_unfinished_content: "Sie haben das Formular noch nicht vollständig ausgfüllt, möchten Sie es trotzdem absenden? Je mehr Fragen Sie beantworten, desto individueller können die Empfehlungen berechnet werden.",
    form_send: "Absenden",
    form_layout_questions: "Fragenlayout",
    form_help: "Hilfe",
    form_input_placeholder: "Hier eingeben...",

    evaluation_information_title: "Infos zur Bewertung",
    evaluation_information_text: "Hier sehen Sie die auf der Basis Ihrer Anworten gewichteten Maßnahmen. Möchten Sie sich über eine dieser Maßnahmen informieren, so tippen Sie diese einfach an.",
    evaluation_list_heading: "Die Bewertung:",
    evaluation_loading: "Die Bewertung wird durchgeführt...",
    evaluation_loading_error: "Aktuell kann die Bewertung nicht durchgefürt werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
    evaluation_loading_empty: "Die Auswertung konnte aktuell keine Maßnahmen finden. Bitte überprüfen Sie Ihre Eingaben, beantworten Sie weitere Fragen oder versuchen Sie es später erneut.",
    evaluation_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Auswertung kann daher nicht durchgeführt werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
    evaluation_help: "Fragen? Jetzt Kontakt aufnehmen ",
    evaluation_split_content_placeholder: "Wählen Sie eine Maßnahme aus der Liste aus, um weitere Informationen anzuzeigen.",
    evaluation_generate_pdf: "PDF erstellen",

    evaluation_detail_loading: "Die Maßnahme wird geladen...",
    evaluation_detail_loading_error: "Aktuell kann die Maßnahme leider nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
    evaluation_detail_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Details zur Maßnahme können daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",

    medialibrary: "Erklärvideos",
    medialibrary_loading: "Laden der verfügbaren Erklärvideos...",
    medialibrary_loading_error: "Aktuell können keine Videos geladen werden. Bitte überprüfen Sie Ihre Internetverbindungoder versuchen Sie es später erneut.",
    medialibrary_loading_empty: "Erklärvideos des Kompetenzzentrums werden hier angezeigt. Aktuell wurden keine Videos gefunden. Bitte versuchen Sie es später erneut.",
    medialibrary_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Videos können daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
    medialibrary_watch_now: "Jetzt ansehen",
    medialibrary_card_title: "Zur SmartFarmCheck-Mediathek",
    medialibrary_card_description: "Hier finden Sie unseren allgemeinen Erklär- und Infovideos, die unabhängig von konkreten Digialisierungsmaßnahmen verschiedene interessante Themen behandeln.",
    medialibrary_heading: "Alle Erklärvideos:",

    event_calendar: "Veranstaltungskalendar",
    event_list_heading: "Kommende Veranstaltungen",
    event_loading: "Laden der kommenden Veranstaltungen...",
    event_loading_error: "Aktuell können keine Veranstaltungen geladen werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
    event_loading_empty: "Kommende Veranstaltungen des Kompetenzzentrums werden hier angezeigt. Aktuell stehen keine Veranstaltungen an.",
    event_loading_no_network: "Aktuell besteht keine Internetverbindung. Die Veranstaltungen können daher nicht geladen werden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",

    event_already_in_calendar_title: "Veranstaltung bereits eingetragen",
    event_already_in_calendar_text: "Im Kalender ist bereits eine Veranstaltung mit gleichem Namen und gleichen Zeiten eingetragen, sie wird daher nicht erneut gespeichert.",

    calendar_create_new: "[Neuen Kalender erstellen]",
    permission_calendar: "Kalenderberechtigung",
    permission_calendar_denied: "Fehlende Kalenderberechtigung",
    permission_calendar_information_before: "Nachfolgend wird die Systemberechtigung zum Bearbeiten der Kalender abgefragt. Diese wird benötigt, um automatisch Termine in Ihren Kalender einzutragen.",
    permission_calendar_information_before_denied_permanent: "Sie scheinen die Kalenderberechtigung abgelehnt zu haben, weswegen wir Ihnen leider keine Termine automatisch in Ihren Kalender eintragen dürfen. Sie können diese manuell in den Systemeinstellungen erteilen.",
    permission_calendar_information_after_denied: "Ohne die Berechtigung können wir die Termine für Sie leider nicht in Ihren Kalender eintragen. Alternativ können Sie den Termin natürlich manuell eintragen, oder die Berechtigung bei der nächsten Abfrage erteilen.",
    permission_calendar_information_after_denied_permanent: "Ohne die Berechtigung können wir die Termine für Sie leider nicht in Ihren Kalender eintragen. Wenn Sie sich dennoch umentscheiden können Sie die Berechtigung in den Berechtigungseinstellung Ihres System ändern.",
    settings_appearance_title: "Helles/dunkels Design",
    settings_appearance_description: "Das Design der App passt sich automatisch den eingestellten Präferenzen Ihres Gerätes an.",
    settings_reset_form_title: "Formulare zurücksetzen",
    settings_reset_form_description: "Setzen Sie Ihre Eingaben in allen Formularen zurück.",
    settings_reset_form_dialog_title: "Alle Formulare zurücksetzen?",
    settings_reset_form_dialog_content: "Sind Sie sicher, dass Sie alle Formulare zurücksetzen möchten?",
    settings_licenses_title: "Lizenzen",
    settings_licenses_description: "Eine Übersicht der verwendeten Open-Source-Bibliothken.",

    contact_mail_title: "Per Mail",
    contact_mail_description: "Bei allgemeinen Fragen können Sie uns jederzeit per Mail erreichen. Wir werden uns dann entsprechend bei Ihnen zurückmelden.",
    contact_mail_action: "Jetzt E-Mail verfassen",
    contact_phone_title: "Telefonisch",
    contact_phone_description: "Natürlich können Sie uns auch telefonisch zu den normalen Bürozeiten erreichen.",
    contact_mail_contact: "Nikolas Neddermann\nTel: 0541-969-5017",
    contact_phone_action: "Jetzt anrufen",
    contact_information_title: "Informationen zur App",
    contact_information_description: "Informationen über Förderer, Impressum und Datenschutz.",
    contact_information_action: "Anzeigen",

    contact_request_loading_error: "Fehler beim Erstellen einer Kontaktanfrage.",
    contact_request_loading_no_network: "Aktuell besteht keine Internetverbindung.",
    contact_request_loading: "Kontaktanfrage wird erstellt...",
    contact_request_success: "Die Kontaktanfrage wurde erfolgreich erstellt. Sie sehen diese dann in Ihrem E-Mail-Postfach sehen. Das Versenden der Kontaktanfrage kann einige Minuten in Anspruch nehmen.",
    contact_request_dialog_empty_title: "Leeres Formular",
    contact_request_dialog_empty_content: "Bein einem gänzlich unausgefülltem Fragebogen wählen Sie bitte den normalen Kontaktweg über die Kontaktoptionen auf dem Kontaktmenüpunkt der Startseite. Sobald Sie einige Fragen beantwortet haben, können Sie auch diesen Kontaktweg verwenden.",
    
}

export default Strings
